name: 'Cloud Propeller, LLC'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#de347f'
    - '#000000'
    - '#454343'
    - '#afafaf'
  brandStrength: 0.6966241321060807
  lightness: 0.17874602763913572
  saturation: 0.3368521670345217
  rhythmicContrast: 0.08639238751493394
purpose: []
